[package]
name = "haxo001"
version = "0.1.0"
authors = ["Javier Cardona <javier.cardona@gmail.com>"]
description = "haxophone software"
edition = "2018"
license = "mit"

[dependencies]
alsa = "0.11.0"
env_logger = "0.11.11"
log = "0.4.14"
midir = "0.11.0"
rand = "0.10.2"
rppal = { version = "0.22.1", features = ["hal"] }
serde_json = "1.0"
schedule_recv = "0.1"
static_assertions = "1.1.0"
structopt = "0.3.22"
time = "0.3.55"
fluidlite = { version = "0.2.1", features = ["builtin"] }
thread-priority = "3.1.1"

[dev-dependencies]
test-log = "0.2.12"

[build-dependencies]
vergen = { version = "8.2.6", features = ["git", "gitcl"] }

[features]
default = []
# Enable timing measurements via GPIO (UART_RXD).  Cannot be enabled when serial
# console is used.
instrumentation = []
midi = []

# Configuration for cargo-deb.
[package.metadata.deb]
assets = [
  ["target/release/haxo001", "usr/local/bin/", "755"],
  ["scripts/systemd/create_midi_gadget.sh", "usr/local/bin/", "755"],
  ["notemap.json", "usr/share/haxo/", "644"],
  ["midi/startup/Startup_Haxophone.mid", "usr/share/haxo/", "644"],
]
maintainer-scripts = "scripts/systemd"
systemd-units = [
  { unit-name = "haxo", enable = true },
  { unit-name = "blink-zero", enable = true },
]
depends = ["libasound2", "timgm6mb-soundfont", "fluid-soundfont-gm"]
